"""empty message

Revision ID: bfbb816d1f9d
Revises: 
Create Date: 2025-08-27 17:25:59.859314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfbb816d1f9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meshnodes',
    sa.Column('data', sa.String(length=8), nullable=False),
    sa.Column('ora', sa.String(length=8), nullable=False),
    sa.Column('nodenum', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=9), nullable=False),
    sa.Column('longname', sa.String(length=28), nullable=False),
    sa.Column('alt', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('batt', sa.Integer(), nullable=False),
    sa.Column('snr', sa.Float(), nullable=False),
    sa.Column('pressione', sa.Float(), nullable=False),
    sa.Column('temperat', sa.Float(), nullable=False),
    sa.Column('umidita', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('nodenum')
    )
    op.create_table('messaggi',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=8), nullable=False),
    sa.Column('ora', sa.String(length=8), nullable=False),
    sa.Column('msg', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('modes',
    sa.Column('node_id', sa.String(length=9), nullable=False),
    sa.Column('nome', sa.String(length=28), nullable=False),
    sa.Column('freq', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=14), nullable=False),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_table('tracking',
    sa.Column('node_id', sa.String(length=9), nullable=False),
    sa.Column('longname', sa.String(length=28), nullable=False),
    sa.Column('data', sa.String(length=8), nullable=False),
    sa.Column('ora', sa.String(length=8), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('alt', sa.Integer(), nullable=False),
    sa.Column('batt', sa.Integer(), nullable=False),
    sa.Column('temperat', sa.Float(), nullable=False),
    sa.Column('pressione', sa.Float(), nullable=False),
    sa.Column('umidita', sa.Float(), nullable=False),
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracking')
    op.drop_table('modes')
    op.drop_table('messaggi')
    op.drop_table('meshnodes')
    # ### end Alembic commands ###
